/* ─── Dashboard styles (ds) ─────────────────────────────────────────────────── */
export const ds = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.9rem',
    paddingTop: '1.5rem',
  },
  header: { marginBottom: '0.1rem' },
  rule: { height: 1, background: 'var(--border-color)', margin: '0.15rem 0 0.25rem' },
  backBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--secondary-color)',
    fontWeight: 600,
    fontSize: '0.9rem',
    cursor: 'pointer',
    padding: '0 0 0.65rem 0',
    display: 'block',
  },
  tripName: {
    margin: 0,
    fontSize: '1.55rem',
    fontWeight: 800,
    color: 'var(--text-color)',
    letterSpacing: '-0.02em',
  },
  card: {
    background: 'var(--card-bg)',
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '1rem',
    boxShadow: '0 1px 4px rgba(0,0,0,0.05)',
  },
  sectionTitle: { margin: 0, marginBottom: '0.6rem', fontSize: '1rem', fontWeight: 700 },
  activitySection: {
    width: '100%',
    maxWidth: 520,
    margin: '0 auto',
    padding: '0.35rem 0 0.15rem',
    background: 'transparent',
    border: 'none',
    boxShadow: 'none',
  },
  activityTitle: {
    margin: 0,
    marginBottom: '0.65rem',
    fontSize: '1rem',
    fontWeight: 700,
    textAlign: 'center',
  },
  membersLine: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.65rem',
    flexWrap: 'nowrap',
    overflowX: 'auto',
    paddingBottom: '0.2rem',
  },
  membersLabel: { margin: 0, fontSize: '1rem', fontWeight: 700, whiteSpace: 'nowrap' },
  membersText: { fontSize: '0.95rem', color: 'var(--text-color)' },
  memberName: { fontWeight: 700 },
  memberDivider: { color: 'var(--light-text)' },
  addMemberBtn: {
    background: '#eef6ff',
    border: '1px solid var(--secondary-color)',
    borderRadius: '8px',
    padding: '0.35rem 0.72rem',
    cursor: 'pointer',
    color: 'var(--secondary-color)',
    fontWeight: 600,
    fontSize: '0.85rem',
  },
  balanceIntro: {
    margin: '-0.35rem 0 0.85rem',
    fontSize: '0.82rem',
    color: 'var(--light-text)',
    lineHeight: 1.45,
  },
  balanceColumns: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '1rem',
    alignItems: 'stretch',
  },
  balancePanel: {
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '1rem 1.05rem',
    background: '#fafcff',
    minWidth: 0,
  },
  balancePanelOwe: {
    borderTop: '3px solid #007bff',
  },
  balancePanelOwed: {
    borderTop: '3px solid #42d6a3',
  },
  balancePanelLabel: {
    fontSize: '0.72rem',
    fontWeight: 700,
    color: 'var(--light-text)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '0.2rem',
  },
  balancePanelTotal: {
    margin: 0,
    fontSize: '1.42rem',
    fontWeight: 800,
    color: 'var(--text-color)',
    letterSpacing: '-0.02em',
    fontFamily: 'var(--font-title)',
  },
  balancePanelRule: {
    height: 1,
    background: 'var(--border-color)',
    margin: '0.65rem 0 0.5rem',
  },
  balancePanelSub: {
    fontSize: '0.72rem',
    fontWeight: 700,
    color: 'var(--light-text)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '0.4rem',
  },
  balanceBreakdownList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.28rem',
  },
  balanceBreakdownItem: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    alignItems: 'baseline',
    gap: '0.65rem',
    fontSize: '0.88rem',
    color: 'var(--text-color)',
  },
  balanceBreakdownName: {
    fontWeight: 700,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  balanceBreakdownAmount: {
    fontWeight: 800,
    color: 'var(--text-color)',
    whiteSpace: 'nowrap',
    textAlign: 'right',
    fontVariantNumeric: 'tabular-nums',
  },
  balanceBreakdownEmpty: {
    margin: 0,
    fontSize: '0.84rem',
    color: 'rgba(102, 114, 148, 0.55)',
    fontStyle: 'italic',
  },
  activityList: { display: 'flex', flexDirection: 'column', gap: '0.42rem' },
  activityRow: { margin: 0, fontSize: '0.93rem' },
  activityUser: { fontWeight: 700 },
  activityMeta: { color: 'rgba(102, 114, 148, 0.52)' },
  activityAmount: { color: '#000', fontWeight: 800 },
  expenseOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(7, 14, 40, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1rem',
    zIndex: 1200,
  },
  expenseModal: {
    width: '100%',
    maxWidth: 820,
    background: 'var(--card-bg)',
    border: '1px solid var(--border-color)',
    borderRadius: '16px',
    boxShadow: '0 20px 50px rgba(7, 14, 40, 0.25)',
    padding: '1.25rem',
  },
  expenseModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.35rem',
  },
  expenseCloseBtn: {
    border: 'none',
    background: 'none',
    color: 'var(--light-text)',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0.2rem',
  },
  expenseForm: { display: 'flex', flexDirection: 'column', gap: '0.6rem' },
  expenseFieldLabel: {
    display: 'block',
    fontSize: '0.82rem',
    fontWeight: 700,
    color: 'var(--text-color)',
    marginBottom: '0.35rem',
  },
  expensePeopleRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '1rem 1.25rem',
    alignItems: 'flex-start',
  },
  expensePeopleCol: {
    flex: '1 1 220px',
    minWidth: 0,
  },
  memberChipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.4rem',
  },
  memberChip: {
    border: '1px solid var(--secondary-color)',
    background: '#e8fafc',
    color: 'var(--secondary-color)',
    borderRadius: '999px',
    padding: '0.32rem 0.65rem',
    fontSize: '0.78rem',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    lineHeight: 1.2,
  },
  memberChipActive: {
    background: 'var(--secondary-color)',
    color: '#fff',
    borderColor: 'var(--secondary-color)',
  },
  expenseHint: {
    margin: '0.15rem 0 0',
    fontSize: '0.76rem',
    color: 'var(--light-text)',
    lineHeight: 1.4,
  },
  expenseInlineRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '0.65rem',
    alignItems: 'stretch',
    width: '100%',
  },
  expenseInput: {
    width: '100%',
    padding: '0.68rem 0.8rem',
    border: '1px solid var(--border-color)',
    borderRadius: '9px',
    fontSize: '0.92rem',
    color: 'var(--text-color)',
    background: '#fff',
  },
  expenseInputAmount: {
    flex: '0 0 7.25rem',
    width: 'auto',
    minWidth: '6.5rem',
  },
  expenseInputPurpose: {
    flex: '1 1 12rem',
    width: 'auto',
    minWidth: '8rem',
  },
  expenseError: { margin: 0, color: '#c62828', fontSize: '0.85rem' },
  expenseActions: { display: 'flex', gap: '0.65rem', alignItems: 'center' },
  expenseCancelBtn: {
    border: 'none',
    background: 'none',
    padding: '0.35rem 0.5rem',
    margin: 0,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: '0.92rem',
    fontWeight: 600,
    color: '#c62828',
  },
  actions: { display: 'flex', flexDirection: 'column', gap: '0.56rem' },
  addExpenseBtn: {
    width: '100%',
    background: '#e8fafc',
    border: '1px solid var(--secondary-color)',
    borderRadius: '12px',
    padding: '0.75rem 1.1rem',
    cursor: 'pointer',
    color: 'var(--secondary-color)',
    fontWeight: 600,
    fontSize: '0.92rem',
    fontFamily: 'inherit',
    boxShadow: 'none',
  },
  secondaryRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: '0.5rem',
    width: '100%',
    alignItems: 'stretch',
  },
  secondaryBtnRow: {
    flex: 1,
    minWidth: 0,
    padding: '0.72rem 0.4rem',
    border: 'none',
    borderRadius: '9px',
    fontSize: '0.78rem',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    textAlign: 'center',
    lineHeight: 1.25,
    boxShadow: '0 4px 12px rgba(42, 64, 149, 0.14)',
    transition: 'filter 0.15s, transform 0.1s',
  },
  secondaryBtnBlue: {
    background: '#007bff',
    color: '#fff',
    boxShadow: '0 6px 18px rgba(0, 123, 255, 0.32)',
  },
  secondaryBtnGreen: {
    background: '#42d6a3',
    color: '#fff',
    boxShadow: '0 6px 18px rgba(50, 190, 145, 0.32)',
  },
  secondaryBtnYellow: {
    background: '#ffc107',
    color: '#212529',
    boxShadow: '0 6px 18px rgba(255, 193, 7, 0.35)',
  },
  spinner: {
    width: 32,
    height: 32,
    border: '3px solid var(--border-color)',
    borderTopColor: 'var(--secondary-color)',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
    margin: '0 auto',
  },
  activityRowContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.2rem 0',
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#ff4d4d',
    cursor: 'pointer',
    fontSize: '0.85rem',
    fontWeight: 'bold',
    padding: '4px 8px',
    borderRadius: '4px',
    transition: 'background 0.2s',
  },
};

/* ─── Modal styles (ms) ──────────────────────────────────────────────────────── */
export const ms = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex', alignItems: 'flex-end',
    zIndex: 100,
  },
  sheet: {
    background: 'var(--card-bg)',
    width: '100%', maxWidth: 600, margin: '0 auto',
    borderRadius: '18px 18px 0 0',
    padding: '1rem 1.5rem 2rem',
    boxShadow: '0 -4px 30px rgba(0,0,0,0.15)',
  },
  sheetHandle: {
    width: 36, height: 4, borderRadius: 2,
    background: 'var(--border-color)',
    margin: '0 auto 1rem',
  },
  sheetHeader: {
    display: 'flex', justifyContent: 'space-between',
    alignItems: 'center', marginBottom: '0.25rem',
  },
  sheetTitle: { margin: 0, fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-color)' },
  closeBtn: {
    background: 'none', border: 'none',
    color: 'var(--light-text)', fontSize: '1rem', cursor: 'pointer', padding: 0,
  },
  sheetSub: { fontSize: '0.82rem', color: 'var(--light-text)', marginBottom: '1rem' },

  searchRow: { display: 'flex', gap: '0.5rem', marginBottom: '0.75rem' },
  searchInput: {
    flex: 1, padding: '0.6rem 0.75rem',
    border: '1px solid var(--border-color)',
    borderRadius: '6px', fontSize: '0.9rem',
    outline: 'none',
  },
  searchBtn: {
    padding: '0.6rem 1rem',
    background: 'var(--secondary-color)', color: '#fff',
    border: 'none', borderRadius: '6px',
    fontWeight: 600, fontSize: '0.88rem', cursor: 'pointer',
  },

  feedback: { fontSize: '0.82rem', color: 'var(--primary-color)', margin: '0 0 0.5rem' },

  resultList: { listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.4rem' },
  resultItem: {
    display: 'flex', alignItems: 'center', gap: '0.6rem',
    padding: '0.5rem 0',
    borderBottom: '1px solid var(--border-color)',
  },
  resultAvatar: {
    width: 32, height: 32, borderRadius: '50%',
    background: 'var(--secondary-color)',
    color: '#fff', display: 'flex', alignItems: 'center',
    justifyContent: 'center', fontSize: '0.75rem',
    fontWeight: 700, flexShrink: 0,
  },
  resultName: { flex: 1, fontSize: '0.88rem', fontWeight: 500, color: 'var(--text-color)' },
  addBtn: {
    padding: '0.3rem 0.8rem',
    background: 'var(--primary-color)', color: '#fff',
    border: 'none', borderRadius: '5px',
    fontWeight: 600, fontSize: '0.8rem', cursor: 'pointer',
  },
};
